# Generated by Django 4.1.7 on 2024-03-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_product_explaination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='explaination',
            new_name='explanation',
        ),
    ]
